export  const LOGIN ="LOGIN"
export  const REGISTER ="REGISTER"
export  const ACTIVATE ="ACTIVATE";
export const LOGOUT="LOGOUT";
export const USER_REGISTER_ERRORS= "USER_REGISTER_ERRORS";
export const USER_ACTIVATION_ERRORS = "USER_ACTIVATION_ERRORS";
export const USER_LOGIN_ERRORS = "USER_LOGIN_ERRORS";
